hs1 driving code
schmaenjael/ecer-botball-2023 pull request #7
Opened 2023-03-15 12:38 UTC by dwaltsch

2023-03-15 12:49 UTC, schmaenjael requested changes
Take a look at the comments, please!

2023-03-15 12:49 UTC, schmaenjael commented on src/lego_robot/main.c
> +void bring_poms_to_Analysis_Center();
Lowercase "analysis center"!

2023-03-15 12:49 UTC, schmaenjael commented on src/lego_robot/main.c
> +    printf("poms zum analyse cetner wuerd ufgrueafa \n");
What is meant by this? Is this soley used for debugging? If so, please remove.

2023-03-15 12:49 UTC, schmaenjael commented on src/lego_robot/main.c
> +boolean is_over_black_line = false;
Is this variable actually getting used? Why is it defined globally and not within scope?

2023-03-16 19:40 UTC, dwaltsch reviewed
good

2023-03-16 19:40 UTC, dwaltsch reviewed
.

2023-03-16 19:49 UTC, schmaenjael approved these changes
lgtm, better commit messages in the future!

2023-03-16 19:50 UTC, merged